# Generated by Django 5.2.7 on 2025-10-08 08:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_alter_businesslisting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card', models.FileField(blank=True, help_text='Upload PAN card for verification', null=True, upload_to='verification/pan/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('citizenship', models.FileField(blank=True, help_text='Upload your citizenship certificate', null=True, upload_to='verification/citizenship/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('pan_number', models.CharField(blank=True, help_text='PAN number from your PAN card', max_length=25)),
                ('citizenship_number', models.CharField(blank=True, help_text='Citizenship ID number', max_length=25)),
                ('owner_name', models.CharField(blank=True, help_text='Owner name as per official documents', max_length=100)),
                ('has_valid_metatags', models.BooleanField(default=False, help_text='Auto-checked or manually confirmed')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('is_email_domain_verified', models.BooleanField(default=False)),
                ('email_otp', models.CharField(blank=True, max_length=6)),
                ('email_otp_created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email_otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_pan_verified', models.BooleanField(default=False)),
                ('is_citizenship_verified', models.BooleanField(default=False)),
                ('is_fully_verified', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='listings.businesslisting')),
            ],
            options={
                'verbose_name': 'Business Verification',
                'verbose_name_plural': 'Business Verifications',
            },
        ),
    ]
