# Generated by Django 5.2.6 on 2025-09-23 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_alter_businesslisting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.businesslisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('directions', 'Directions')], max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='listings.businesslisting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ranking_score', models.FloatField(default=0.0, help_text='Computed score for sorting')),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='1=most_popular', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rankings', to='listings.businesslisting')),
            ],
            options={
                'ordering': ['-year', '-month', 'ranking'],
                'indexes': [models.Index(fields=['-year', '-month'], name='analytics_m_year_81486e_idx'), models.Index(fields=['-ranking_score'], name='analytics_m_ranking_bd7149_idx'), models.Index(fields=['business', '-year', '-month'], name='analytics_m_busines_e036ec_idx')],
                'unique_together': {('business', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ranking_score', models.FloatField(default=0.0, help_text='Computed score for sorting')),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='1=most_popular', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rankings', to='listings.businesslisting')),
            ],
            options={
                'ordering': ['week_start', 'ranking'],
                'indexes': [models.Index(fields=['week_start'], name='analytics_w_week_st_a28491_idx'), models.Index(fields=['-ranking_score'], name='analytics_w_ranking_f91e4c_idx'), models.Index(fields=['business', 'week_start'], name='analytics_w_busines_c2803b_idx')],
                'unique_together': {('business', 'week_start')},
            },
        ),
    ]
