# Generated by Django 5.2.6 on 2025-09-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='views', to='listings.businesslisting')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('website', 'Website')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='listings.businesslisting')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('month_start', models.DateField()),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('click_count', models.PositiveBigIntegerField(default=0)),
                ('ranking', models.PositiveBigIntegerField(help_text='1=most_popular')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_ranking', to='listings.businesslisting')),
            ],
            options={
                'ordering': ['-year', '-month_start', 'ranking'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('click_count', models.PositiveBigIntegerField(default=0)),
                ('ranking', models.PositiveBigIntegerField(help_text='1=most_popular')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekely_ramking', to='listings.businesslisting')),
            ],
            options={
                'ordering': ['week_start', 'ranking'],
            },
        ),
    ]
