# Generated by Django 5.2.6 on 2025-09-21 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Review written by the user', limit_choices_to={'user_type__in': ['normal', 'owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_reviews', to='userprofile.user')),
                ('business', models.ForeignKey(help_text='The business being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.businesslisting')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'author')},
            },
        ),
        migrations.CreateModel(
            name='ReportedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(help_text='User who reported the review', on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to='userprofile.user')),
                ('reviewed', models.ForeignKey(help_text='The review being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='businessreview.review')),
            ],
            options={
                'verbose_name': 'Reported Review',
                'verbose_name_plural': 'Reported Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
