# Generated by Django 5.2.6 on 2025-09-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessreview', '0002_reviewreply_reportedreview_resolved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating_cleanliness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating_price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating_service',
        ),
    ]
