# Generated by Django 5.2.6 on 2025-09-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessreview', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='media',
            field=models.FileField(blank=True, upload_to='reviews/'),
        ),
    ]
