# Generated by Django 5.2.6 on 2025-09-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='listings.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business_name', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('website', models.URLField(blank=True)),
                ('social_links', models.URLField(blank=True, default=dict)),
                ('address_province', models.CharField(blank=True, max_length=100, null=True)),
                ('address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('address_ward', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='business_covers/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejection', 'Rejection')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='If rejected, why?')),
                ('is_featured', models.BooleanField(default=False, help_text='Paid promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owners', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='userprofile.user')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Business Listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
