# Generated by Django 5.2.6 on 2025-09-22 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Listing', 'verbose_name_plural': 'Business Listings'},
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='address_municipality',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='address_province',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='address_ward',
        ),
        migrations.RemoveField(
            model_name='businesslisting',
            name='owners',
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of business, services, history, etc.'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='has_multiple_locations',
            field=models.BooleanField(default=False, help_text='Does this business operate from multiple branches?'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom meta description for search engines', null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom title for search engines', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this business listing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='verified_badge',
            field=models.BooleanField(default=False, help_text='Blue checkmark — verified by admin'),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Banner image (1200x400px)', null=True, upload_to='business_covers/'),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='email',
            field=models.EmailField(blank=True, help_text='Business contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Is this a paid/promoted listing?'),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Square logo (200x200px)', null=True, upload_to='business_logos/'),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='name',
            field=models.CharField(help_text='Official business name', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact number', max_length=15),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object of social media URLs, e.g., {"facebook": "https://...", "instagram": "..."}'),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='listings.businesslisting')),
            ],
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='primary_location',
            field=models.ForeignKey(blank=True, help_text='Main/default location for display purposes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='listings.businesslocation'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='category',
            field=models.ForeignKey(default=True, help_text='Main category (e.g., Restaurant, Salon)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category'),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Specific subcategory (e.g., Italian Restaurant, Hair Salon)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.subcategory'),
        ),
    ]
