# Generated by Django 5.2.6 on 2025-09-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_businesslisting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Main category (e.g., Restaurant, Salon)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category'),
        ),
    ]
