# Generated by Django 5.2.6 on 2025-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_businesslisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
