# Generated by Django 5.2.6 on 2025-09-25 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_businesslocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Square logo (200x200px)', null=True, upload_to='business_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
