# Generated by Django 5.2.6 on 2025-09-21 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(help_text='Recommended size: 728x90 or 300x250', upload_to='ads/banners/')),
                ('url', models.URLField(help_text='where the banner links to')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner?')),
                ('position', models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_bottom', 'Homepage Bottom'), ('category_top', 'Category Page Top'), ('category_bottom', 'Category Page Bottom')], default='homepage_top', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(help_text='When ad expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Ad',
                'verbose_name_plural': 'Banner Ads',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(help_text='when promotion expires')),
                ('is_active', models.BooleanField(default=True, help_text='Currently featured?')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='paid_amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(help_text='Business is being promoted', on_delete=django.db.models.deletion.CASCADE, related_name='featured_promotion', to='listings.businesslisting')),
            ],
            options={
                'verbose_name': 'Featured Listing',
                'verbose_name_plural': 'Featured Listings',
                'ordering': ['-start_date'],
            },
        ),
    ]
