# Generated by Django 5.2.7 on 2025-10-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adclick_cupon_flashdeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='valid_form',
            new_name='valid_from',
        ),
    ]
