# Generated by Django 5.2.6 on 2025-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('normal', 'Normal User'), ('owner', 'Business Owner'), ('admin', 'Admin')], default='normal', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('address_province', models.CharField(blank=True, max_length=100, null=True)),
                ('address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('address_ward', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
