# Generated by Django 5.2.6 on 2025-09-22 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessreview', '0002_reviewreply_reportedreview_resolved_at_and_more'),
        ('listings', '0002_alter_businesslisting_options_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('listing_submitted', 'Listing Submitted'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('new_review', 'New Review Posted'), ('review_reported', 'Review Reported'), ('promotion_approved', 'Promotion Approved'), ('coupon_redeemed', 'Coupon Redeemed'), ('location_added', 'New Location Added'), ('featured_listing_approved', 'Featured Listing Approved'), ('banner_ad_approved', 'Banner Ad Approved'), ('reply_to_review', 'Reply to Your Review')], max_length=50)),
                ('related_promotion', models.CharField(blank=True, help_text="e.g., 'Coupon:SUMMER20' or 'FlashDeal:WeekendSale'", max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='in_app', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.businesslisting')),
                ('related_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businessreview.review')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_enabled', models.JSONField(default=list, help_text='List of event_type keys user wants to receive')),
                ('delivery_channels', models.JSONField(default=list, help_text="e.g., ['email', 'push']")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationLog',
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['recipient', 'read_status'], name='notificatio_recipie_80ec56_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['event_type'], name='notificatio_event_t_be70d3_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['-sent_at'], name='notificatio_sent_at_dfcee4_idx'),
        ),
    ]
